const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
  query: (p) => ipcRenderer.invoke('polaris:query', p),
  queryStream: (p) => ipcRenderer.invoke('polaris:queryStream', p),
  onStreamChunk: (cb) => { ipcRenderer.on('polaris:stream-chunk', (_, d) => cb(d)); },
  onStreamEnd: (cb) => { ipcRenderer.on('polaris:stream-end', (_, d) => cb(d)); },
  onStreamError: (cb) => { ipcRenderer.on('polaris:stream-error', (_, d) => cb(d)); },
  removeStreamListeners: () => { ipcRenderer.removeAllListeners('polaris:stream-chunk'); ipcRenderer.removeAllListeners('polaris:stream-end'); ipcRenderer.removeAllListeners('polaris:stream-error'); },
  minimize: () => ipcRenderer.invoke('window:minimize'), maximize: () => ipcRenderer.invoke('window:maximize'), close: () => ipcRenderer.invoke('window:close'),
  getVersion: () => ipcRenderer.invoke('get-version'), openExternal: (u) => ipcRenderer.invoke('open-external', u),
  desktopScreenshot: () => ipcRenderer.invoke('desktop:screenshot'), desktopListWindows: () => ipcRenderer.invoke('desktop:listWindows'),
  desktopFocusWindow: (t) => ipcRenderer.invoke('desktop:focusWindow', t), desktopOpenApp: (p) => ipcRenderer.invoke('desktop:openApp', p),
  desktopOpenBrowser: (u) => ipcRenderer.invoke('desktop:openBrowser', u), desktopOpenExplorer: (d) => ipcRenderer.invoke('desktop:openExplorer', d),
  desktopTypeText: (t) => ipcRenderer.invoke('desktop:typeText', t), desktopPressKey: (k) => ipcRenderer.invoke('desktop:pressKey', k),
  desktopHotkey: (c) => ipcRenderer.invoke('desktop:hotkey', c), desktopMoveMouse: (x,y) => ipcRenderer.invoke('desktop:moveMouse', x, y),
  desktopClickMouse: (x,y,b) => ipcRenderer.invoke('desktop:clickMouse', x, y, b), desktopDoubleClick: (x,y) => ipcRenderer.invoke('desktop:doubleClick', x, y),
  desktopScrollMouse: (d,a) => ipcRenderer.invoke('desktop:scrollMouse', d, a), desktopGetClipboard: () => ipcRenderer.invoke('desktop:getClipboard'),
  desktopSetClipboard: (t) => ipcRenderer.invoke('desktop:setClipboard', t), desktopSystemInfo: () => ipcRenderer.invoke('desktop:systemInfo'),
  desktopListFiles: (d) => ipcRenderer.invoke('desktop:listFiles', d), desktopReadFile: (f) => ipcRenderer.invoke('desktop:readFile', f),
  desktopWriteFile: (f,c) => ipcRenderer.invoke('desktop:writeFile', f, c), desktopRunCommand: (c) => ipcRenderer.invoke('desktop:runCommand', c),
  desktopAgentStep: (p) => ipcRenderer.invoke('desktop:agentStep', p),
  mcpStart: (p) => ipcRenderer.invoke('mcp:start', p), mcpStop: (id) => ipcRenderer.invoke('mcp:stop', id), mcpList: () => ipcRenderer.invoke('mcp:list'),
  notify: (p) => ipcRenderer.invoke('notify', p),
});
