const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
  query: (p) => ipcRenderer.invoke('polaris:query', p),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  maximize: () => ipcRenderer.invoke('window:maximize'),
  close: () => ipcRenderer.invoke('window:close'),
  getVersion: () => ipcRenderer.invoke('get-version'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  // Desktop automation
  desktopScreenshot: () => ipcRenderer.invoke('desktop:screenshot'),
  desktopListWindows: () => ipcRenderer.invoke('desktop:listWindows'),
  desktopFocusWindow: (t) => ipcRenderer.invoke('desktop:focusWindow', t),
  desktopOpenApp: (p) => ipcRenderer.invoke('desktop:openApp', p),
  desktopOpenBrowser: (u) => ipcRenderer.invoke('desktop:openBrowser', u),
  desktopOpenExplorer: (d) => ipcRenderer.invoke('desktop:openExplorer', d),
  desktopTypeText: (t) => ipcRenderer.invoke('desktop:typeText', t),
  desktopPressKey: (k) => ipcRenderer.invoke('desktop:pressKey', k),
  desktopHotkey: (c) => ipcRenderer.invoke('desktop:hotkey', c),
  desktopMoveMouse: (x, y) => ipcRenderer.invoke('desktop:moveMouse', x, y),
  desktopClickMouse: (x, y, b) => ipcRenderer.invoke('desktop:clickMouse', x, y, b),
  desktopDoubleClick: (x, y) => ipcRenderer.invoke('desktop:doubleClick', x, y),
  desktopScrollMouse: (d, a) => ipcRenderer.invoke('desktop:scrollMouse', d, a),
  desktopGetClipboard: () => ipcRenderer.invoke('desktop:getClipboard'),
  desktopSetClipboard: (t) => ipcRenderer.invoke('desktop:setClipboard', t),
  desktopSystemInfo: () => ipcRenderer.invoke('desktop:systemInfo'),
  desktopListFiles: (d) => ipcRenderer.invoke('desktop:listFiles', d),
  desktopReadFile: (f) => ipcRenderer.invoke('desktop:readFile', f),
  desktopWriteFile: (f, c) => ipcRenderer.invoke('desktop:writeFile', f, c),
  desktopRunCommand: (c) => ipcRenderer.invoke('desktop:runCommand', c),
  // Agent ReAct loop
  desktopAgentStep: (p) => ipcRenderer.invoke('desktop:agentStep', p),
});
