/**
 * Polaris Embedded Router v0.7 — streaming + non-streaming + multimodal
 */
const https = require('https');

const INTENTS = {
  code_generation:{display:'代码生成',keywords:['代码','编程','debug','函数','算法','重构','API','接口','架构','前端','后端','python','javascript','react','rust','写一个','实现','golang','go','c++','java'],ensemble:false},
  math_reasoning:{display:'数学推理',keywords:['计算','证明','方程','求导','积分','概率','统计','优化','复杂度','数学','公理','推导','收敛'],ensemble:false},
  creative_writing:{display:'创意写作',keywords:['写','文案','翻译','润色','改写','总结','文章','邮件','报告','方案','创意','故事','诗歌','博客','markdown','介绍','发布会','公告','宣传','帮我写','帮我'],ensemble:false},
  research:{display:'深度研究',keywords:['研究','调研','分析报告','对比','综述','趋势','行业','竞品','文献','最新','数据来源','引用','深度'],ensemble:false},
  data_analysis:{display:'数据分析',keywords:['数据','表格','图表','统计','Excel','CSV','可视化','清洗','回归','聚类','pandas','SQL'],ensemble:false},
  high_stakes:{display:'高利害决策',keywords:['投资','股票','基金','医疗','诊断','法律','合同','风险','保险','贷款','买房','遗嘱','诉讼','税务','合规'],ensemble:true},
  general_chat:{display:'通用对话',keywords:['你好','谢谢','天气','今天','怎么样','聊天','推荐','建议','想法','帮','分析','解释','为什么','怎么','如何','有什么','是什么','什么意思','能不能','可以吗','帮忙'],ensemble:false},
};
const MODEL_MATRIX = {
  'deepseek-chat':{provider:'deepseek',display:'DeepSeek V3',cost:'cheap',caps:{code_generation:.85,math_reasoning:.82,creative_writing:.80,research:.82,data_analysis:.82,general_chat:.85,high_stakes:.72}},
  'deepseek-reasoner':{provider:'deepseek',display:'DeepSeek R1',cost:'standard',caps:{code_generation:.90,math_reasoning:.95,creative_writing:.70,research:.82,data_analysis:.80,general_chat:.70,high_stakes:.75}},
  'claude-sonnet-4':{provider:'anthropic',display:'Claude Sonnet 4',cost:'standard',caps:{code_generation:.95,math_reasoning:.85,creative_writing:.95,research:.90,data_analysis:.85,general_chat:.95,high_stakes:.85}},
  'gpt-4o':{provider:'openai',display:'GPT-4o',cost:'standard',caps:{code_generation:.88,math_reasoning:.82,creative_writing:.90,research:.85,data_analysis:.90,general_chat:.90,high_stakes:.80}},
};

function classifyIntent(text){const scores={};let top='general_chat',topScore=0;for(const[i,d]of Object.entries(INTENTS)){let s=0;for(const kw of d.keywords){if(text.toLowerCase().includes(kw.toLowerCase()))s+=1}scores[i]=Math.min(s/3,1);if(scores[i]>topScore){topScore=scores[i];top=i}}return{top_intent:top,display:INTENTS[top]?.display||top,top_confidence:topScore,intents:scores,ensemble_triggered:INTENTS[top]?.ensemble||Object.values(scores).filter(v=>v>.5).length>=3}}
function selectModels(intent,strategy){const c=Object.entries(MODEL_MATRIX).filter(([,d])=>(d.caps[intent]||.5)>.5).map(([id,d])=>({id,display:d.display,...d,score:d.caps[intent]||.5})).sort((a,b)=>b.score-a.score);if(strategy==='ensemble'){const p=[];const prov=new Set();for(const m of c){if(p.length>=3)break;if(!prov.has(m.provider)||p.length<2){p.push(m);prov.add(m.provider)}}return{models:p,rationale:'多模型: '+p.map(x=>x.display).join(', ')}}if(strategy==='cost_optimized'){const cheap=c.filter(x=>x.cost==='cheap'&&x.score>=.7);const best=cheap[0]||c[0];return{models:[best],rationale:'省钱: '+best.display}}const best=c[0];return{models:[best],rationale:'优质: '+best.display}}

function chatDeepSeek(model,messages,apiKey){const key=apiKey||'sk-e5b9674c9662436eb79712ab26c57370';return new Promise((res,rej)=>{const body=JSON.stringify({model,messages,max_tokens:4096,stream:false});const req=https.request({hostname:'api.deepseek.com',path:'/chat/completions',method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key,'Content-Length':Buffer.byteLength(body)},timeout:120000},resp=>{let d='';resp.on('data',c=>d+=c);resp.on('end',()=>{try{res(JSON.parse(d).choices?.[0]?.message?.content||'')}catch(e){rej(new Error('解析失败'))}})});req.on('error',e=>rej(e));req.write(body);req.end()})}
function chatAnthropic(model,messages,apiKey){const key=apiKey||'';return new Promise((res,rej)=>{const sys=messages.find(m=>m.role==='system')?.content||'';const umsgs=messages.filter(m=>m.role!=='system').map(m=>({role:m.role,content:m.content}));const body=JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:4096,system:sys,messages:umsgs});const req=https.request({hostname:'api.anthropic.com',path:'/v1/messages',method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01','Content-Length':Buffer.byteLength(body)},timeout:120000},resp=>{let d='';resp.on('data',c=>d+=c);resp.on('end',()=>{try{res(JSON.parse(d).content?.[0]?.text||'')}catch(e){rej(new Error('解析失败'))}})});req.on('error',e=>rej(e));req.write(body);req.end()})}
function chatOpenAI(model,messages,apiKey){const key=apiKey||'';return new Promise((res,rej)=>{const body=JSON.stringify({model,messages,max_tokens:4096});const req=https.request({hostname:'api.openai.com',path:'/v1/chat/completions',method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key,'Content-Length':Buffer.byteLength(body)},timeout:120000},resp=>{let d='';resp.on('data',c=>d+=c);resp.on('end',()=>{try{res(JSON.parse(d).choices?.[0]?.message?.content||'')}catch(e){rej(new Error('解析失败'))}})});req.on('error',e=>rej(e));req.write(body);req.end()})}

/** Streaming chat — DeepSeek SSE only */
function chatDeepSeekStream(model,messages,apiKey,onChunk){const key=apiKey||'sk-e5b9674c9662436eb79712ab26c57370';return new Promise((res,rej)=>{const body=JSON.stringify({model,messages,max_tokens:4096,stream:true});let full='';const req=https.request({hostname:'api.deepseek.com',path:'/chat/completions',method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key,'Content-Length':Buffer.byteLength(body)},timeout:120000},resp=>{let buf='';resp.on('data',c=>{buf+=c.toString();const lines=buf.split('\n');buf=lines.pop()||'';for(const line of lines){if(line.startsWith('data: ')){const d=line.slice(6).trim();if(d==='[DONE]')continue;try{const j=JSON.parse(d);const delta=j.choices?.[0]?.delta?.content||'';if(delta){full+=delta;onChunk({content:delta,full})}}catch{}}}});resp.on('end',()=>res(full))});req.on('error',e=>rej(e));req.write(body);req.end()})}

async function callModel(modelId,messages){const def=MODEL_MATRIX[modelId];if(!def)throw new Error('未知模型: '+modelId);if(def.provider==='deepseek')return chatDeepSeek(modelId,messages);if(def.provider==='anthropic')return chatAnthropic(modelId,messages);if(def.provider==='openai')return chatOpenAI(modelId,messages);throw new Error('未知供应商: '+def.provider)}

async function executeQuery(text,strategy,systemPrompt,images,onStreamChunk){const classification=classifyIntent(text);const routing=selectModels(classification.top_intent,strategy);const messages=[];if(systemPrompt)messages.push({role:'system',content:systemPrompt});if(images&&images.length>0){const parts=images.map(img=>({type:'image_url',image_url:{url:img}}));parts.unshift({type:'text',text});messages.push({role:'user',content:parts})}else{messages.push({role:'user',content:text})}
  const responses=[];for(const m of routing.models){try{if(onStreamChunk&&m.provider==='deepseek'){const content=await chatDeepSeekStream(m.id,messages,undefined,onStreamChunk);responses.push({model_id:m.id,model_display:m.display,content,latency_ms:0})}else{const content=await callModel(m.id,messages);responses.push({model_id:m.id,model_display:m.display,content,latency_ms:0})}}catch(e){responses.push({model_id:m.id,model_display:m.display,content:'',error:e.message})}}
  return{routing:{strategy,top_intent:classification.display,selected_models:routing.models.map(x=>x.display),rationale:routing.rationale,intent_scores:classification.intents},responses,total_latency_ms:0}}

module.exports={executeQuery};
