const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
  query: (p) => ipcRenderer.invoke('polaris:query', p),
  queryStream: (p) => ipcRenderer.invoke('polaris:queryStream', p),
  onStreamChunk: (cb) => { ipcRenderer.on('polaris:stream-chunk', (_, d) => cb(d)); },
  onStreamEnd: (cb) => { ipcRenderer.on('polaris:stream-end', (_, d) => cb(d)); },
  onStreamError: (cb) => { ipcRenderer.on('polaris:stream-error', (_, d) => cb(d)); },
  removeStreamListeners: () => { ipcRenderer.removeAllListeners('polaris:stream-chunk'); ipcRenderer.removeAllListeners('polaris:stream-end'); ipcRenderer.removeAllListeners('polaris:stream-error'); },
  minimize: () => ipcRenderer.invoke('window:minimize'), maximize: () => ipcRenderer.invoke('window:maximize'), close: () => ipcRenderer.invoke('window:close'),
  getVersion: () => ipcRenderer.invoke('get-version'), openExternal: (u) => ipcRenderer.invoke('open-external', u),
  desktopScreenshot: () => ipcRenderer.invoke('desktop:screenshot'), desktopListWindows: () => ipcRenderer.invoke('desktop:listWindows'),
  desktopFocusWindow: (t) => ipcRenderer.invoke('desktop:focusWindow', t), desktopOpenApp: (p) => ipcRenderer.invoke('desktop:openApp', p),
  desktopOpenBrowser: (u) => ipcRenderer.invoke('desktop:openBrowser', u), desktopOpenExplorer: (d) => ipcRenderer.invoke('desktop:openExplorer', d),
  desktopTypeText: (t) => ipcRenderer.invoke('desktop:typeText', t), desktopPressKey: (k) => ipcRenderer.invoke('desktop:pressKey', k),
  desktopHotkey: (c) => ipcRenderer.invoke('desktop:hotkey', c), desktopMoveMouse: (x,y) => ipcRenderer.invoke('desktop:moveMouse', x, y),
  desktopClickMouse: (x,y,b) => ipcRenderer.invoke('desktop:clickMouse', x, y, b), desktopDoubleClick: (x,y) => ipcRenderer.invoke('desktop:doubleClick', x, y),
  desktopScrollMouse: (d,a) => ipcRenderer.invoke('desktop:scrollMouse', d, a), desktopGetClipboard: () => ipcRenderer.invoke('desktop:getClipboard'),
  desktopSetClipboard: (t) => ipcRenderer.invoke('desktop:setClipboard', t), desktopSystemInfo: () => ipcRenderer.invoke('desktop:systemInfo'),
  desktopListFiles: (d) => ipcRenderer.invoke('desktop:listFiles', d), desktopReadFile: (f) => ipcRenderer.invoke('desktop:readFile', f),
  desktopWriteFile: (f,c) => ipcRenderer.invoke('desktop:writeFile', f, c), desktopRunCommand: (c) => ipcRenderer.invoke('desktop:runCommand', c),
  desktopAgentStep: (p) => ipcRenderer.invoke('desktop:agentStep', p),
  mcpStart: (p) => ipcRenderer.invoke('mcp:start', p), mcpStop: (id) => ipcRenderer.invoke('mcp:stop', id), mcpList: () => ipcRenderer.invoke('mcp:list'),
  notify: (p) => ipcRenderer.invoke('notify', p),
  toolsList: () => ipcRenderer.invoke('tools:list'), toolsExecute: (p) => ipcRenderer.invoke('tools:execute', p), toolsConfirm: (id) => ipcRenderer.invoke('tools:confirm', { confirmId: id }), toolsReject: (id) => ipcRenderer.invoke('tools:reject', { confirmId: id }),
  agentsList: () => ipcRenderer.invoke('agents:list'), workflowsList: () => ipcRenderer.invoke('workflows:list'),
  monitorStart: () => ipcRenderer.invoke('monitor:start'), monitorUpdate: (a) => ipcRenderer.invoke('monitor:update', a), monitorSetScene: (s) => ipcRenderer.invoke('monitor:setScene', s), monitorFeedback: (p) => ipcRenderer.invoke('monitor:feedback', p), monitorContext: () => ipcRenderer.invoke('monitor:context'),
  plannerGenerate: (t) => ipcRenderer.invoke('planner:generate', { text: t }), plannerExecute: (id) => ipcRenderer.invoke('planner:execute', { planId: id }), plannerReject: (id) => ipcRenderer.invoke('planner:reject', { planId: id }),
  onIntervention: (cb) => { ipcRenderer.on('polaris:intervention', (_, d) => cb(d)); },
  onPlanProgress: (cb) => { ipcRenderer.on('polaris:plan-progress', (_, d) => cb(d)); },
  onExecLog: (cb) => { ipcRenderer.on('polaris:exec-log', (_, d) => cb(d)); },
  onTodoUpdate: (cb) => { ipcRenderer.on('polaris:todo-update', (_, d) => cb(d)); },
  healthCheck: () => ipcRenderer.invoke('health:check'),
  sandboxReady: () => ipcRenderer.invoke('sandbox:ready'),
  sandboxNeedsSetup: () => ipcRenderer.invoke('sandbox:needsSetup'),
  sandboxGetProgress: () => ipcRenderer.invoke('sandbox:getProgress'),
  sandboxSetup: () => ipcRenderer.invoke('sandbox:setup'),
  sandboxRepair: () => ipcRenderer.invoke('sandbox:repair'),
  sandboxHealth: () => ipcRenderer.invoke('sandbox:health'),
  sandboxPackages: () => ipcRenderer.invoke('sandbox:packages'),
  sandboxHasPolaris: () => ipcRenderer.invoke('sandbox:hasPolaris'),
  sandboxInstallPackage: (pkg) => ipcRenderer.invoke('sandbox:installPackage', { packageName: pkg }),
  sandboxUninstallPackage: (pkg) => ipcRenderer.invoke('sandbox:uninstallPackage', { packageName: pkg }),
  sandboxAutoSetup: () => ipcRenderer.invoke('sandbox:autoSetup'),
  sandboxRunCode: (code) => ipcRenderer.invoke('sandbox:runCode', { code }),
  sandboxCheckSafety: (code) => ipcRenderer.invoke('sandbox:safety', { code }),
  onSandboxProgress: (cb) => { ipcRenderer.on('sandbox:progress', (_, d) => cb(d)); },
  onGitUpdate: (cb) => { ipcRenderer.on('polaris:git-update', (_, d) => cb(d)); },
  onToolConfirm: (cb) => { ipcRenderer.on('polaris:tool-confirm', (_, d) => cb(d)); },
  onToolConfirmDismiss: (cb) => { ipcRenderer.on('polaris:tool-confirm-dismiss', (_, d) => cb(d)); },
  approvePermission: (id) => ipcRenderer.invoke('tools:approvePermission', { id }),
  approveAlwaysPermission: (id) => ipcRenderer.invoke('tools:approveAlwaysPermission', { id }),
  rejectPermission: (id) => ipcRenderer.invoke('tools:rejectPermission', { id }),
  emailSendCode: (email) => ipcRenderer.invoke('email:sendCode', { email }),
  emailSendWelcome: (email, displayName) => ipcRenderer.invoke('email:sendWelcome', { email, displayName }),
  emailForgotPassword: (email) => ipcRenderer.invoke('email:forgotPassword', { email }),
  authUnlock: (userId) => ipcRenderer.invoke('auth:unlock', { userId }),
  authLock: () => ipcRenderer.invoke('auth:lock'),
  authGithubLogin: (data) => ipcRenderer.invoke('auth:githubLogin', data),
  authGithubLoginLoopback: () => ipcRenderer.invoke('auth:githubLoginLoopback', {}),
  authAdminResetPassword: (email, newPassword) => ipcRenderer.invoke('auth:adminResetPassword', { email, newPassword }),
  authAdminConfirmUser: (email) => ipcRenderer.invoke('auth:adminConfirmUser', { email }),
  authAdminCreateUser: (email, password, displayName) => ipcRenderer.invoke('auth:adminCreateUser', { email, password, displayName }),
  terminalCreate: (type) => ipcRenderer.invoke('terminal:create', { type }),
  terminalWrite: (id, input) => ipcRenderer.invoke('terminal:write', { id, input }),
  terminalRead: (id, lines) => ipcRenderer.invoke('terminal:read', { id, lines }),
  terminalKill: (id) => ipcRenderer.invoke('terminal:kill', { id }),
  flywheelStats: () => ipcRenderer.invoke('flywheel:stats'),
  flywheelExport: (format) => ipcRenderer.invoke('flywheel:export', format),
  routerStats: (problemType) => ipcRenderer.invoke('router:stats', problemType),
  skillgraphEdges: (limit) => ipcRenderer.invoke('skillgraph:edges', limit),
  skillgraphSimilar: (goalText, limit) => ipcRenderer.invoke('skillgraph:similar', goalText, limit),
  skillgraphContext: (goalText) => ipcRenderer.invoke('skillgraph:context', goalText),
  polarisServeStatus: () => ipcRenderer.invoke('polaris-serve:status'),
  polarisModelInstall: () => ipcRenderer.invoke('polaris-model:install'),
  debugState: () => ipcRenderer.invoke('debug:state'),
});
