interface PolarisAPI {
  query(params: { text: string; strategy: string; systemPrompt?: string; images?: string[]; apiKeys?: { deepseek?: string; anthropic?: string; openai?: string } }): Promise<{ routing: { strategy: string; top_intent: string; selected_models: string[]; rationale: string; intent_scores: Record<string, number> }; responses: { model_id: string; model_display?: string; content: string; error?: string }[]; expert_responses?: any[]; subtasks?: any[]; workflow_steps?: { id: string; agent: string; summary: string }[]; ensemble?: any; total_latency_ms: number; }>;
  queryStream(params: { text: string; strategy: string; systemPrompt?: string; images?: string[]; apiKeys?: { deepseek?: string; anthropic?: string; openai?: string } }): Promise<any>;
  onStreamChunk(cb: (data: { content: string; full: string }) => void): void;
  onStreamEnd(cb: (data: any) => void): void; onStreamError(cb: (data: any) => void): void; removeStreamListeners(): void;
  minimize(): Promise<void>; maximize(): Promise<void>; close(): Promise<void>; getVersion(): Promise<string>; openExternal(url: string): Promise<void>;
  desktopScreenshot(): Promise<string|null>; desktopListWindows(): Promise<any[]>; desktopFocusWindow(t: string): Promise<any>;
  desktopOpenApp(p: string): Promise<any>; desktopOpenBrowser(u: string): Promise<any>; desktopOpenExplorer(d: string): Promise<any>;
  desktopTypeText(t: string): Promise<any>; desktopPressKey(k: string): Promise<any>; desktopHotkey(c: string): Promise<any>;
  desktopMoveMouse(x: number, y: number): Promise<any>; desktopClickMouse(x: number, y: number, b?: string): Promise<any>;
  desktopDoubleClick(x: number, y: number): Promise<any>; desktopScrollMouse(d: string, a: number): Promise<any>;
  desktopGetClipboard(): Promise<string>; desktopSetClipboard(t: string): Promise<boolean>; desktopSystemInfo(): Promise<any>;
  desktopListFiles(d: string): Promise<any[]>; desktopReadFile(p: string): Promise<string|null>; desktopWriteFile(p: string, c: string): Promise<any>;
  desktopRunCommand(c: string): Promise<string>; desktopAgentStep(p: { goal: string; screenshot?: string; history?: string }): Promise<{ action: any; raw: string }>; desktopVisionStep(p: { goal: string; history?: any[]; visionKey?: string; visionModel?: string }): Promise<{ screenshot: string | null; action: any; raw: string; error?: string }>;
  mcpStart(p: { id: string; command: string; args: string[]; env?: Record<string,string> }): Promise<{ success: boolean; pid?: number; message?: string }>;
  mcpStop(id: string): Promise<{ success: boolean }>; mcpList(): Promise<{ id: string; pid: number; running: boolean }[]>;
  notify(p: { title: string; body: string }): Promise<boolean>;
  toolsList(): Promise<{ id: string; name: string; description: string; requires_confirm: boolean; category: string }[]>;
  toolsExecute(p: { tool: string; params: Record<string, string> }): Promise<any>;
  toolsConfirm(confirmId: string): Promise<any>; toolsReject(confirmId: string): Promise<any>;
  agentsList(): Promise<{ id: string; name: string; role: string; goal: string; tools: string[] }[]>;
  workflowsList(): Promise<{ id: string; name: string; steps: { id: string; agent: string; description: string }[] }[]>;
  monitorStart(): Promise<{ success: boolean }>; monitorUpdate(a: any): Promise<boolean>; monitorSetScene(s: string): Promise<boolean>; monitorFeedback(p: { eventKey: string; accepted: boolean }): Promise<boolean>; monitorContext(): Promise<any>;
  plannerGenerate(t: string): Promise<any>; plannerExecute(id: string): Promise<any>; plannerReject(id: string): Promise<any>;
  onIntervention(cb: (card: any) => void): void; onPlanProgress(cb: (data: any) => void): void; onExecLog(cb: (data: any) => void): void; onTodoUpdate(cb: (data: any) => void): void;
  healthCheck(): Promise<any>;
  sandboxReady(): Promise<boolean>; sandboxNeedsSetup(): Promise<boolean>; sandboxGetProgress(): Promise<any>;
  sandboxSetup(): Promise<any>; sandboxRepair(): Promise<any>; sandboxHealth(): Promise<any>;
  sandboxPackages(): Promise<any>; sandboxHasPolaris(): Promise<boolean>;
  sandboxInstallPackage(pkg: string): Promise<any>; sandboxUninstallPackage(pkg: string): Promise<any>;
  sandboxAutoSetup(): Promise<any>; sandboxRunCode(code: string): Promise<any>; sandboxCheckSafety(code: string): Promise<any>;
  onSandboxProgress(cb: (data: any) => void): void;
  onGitUpdate(cb: (data: any) => void): void;
  onToolConfirm(cb: (data: any) => void): void; onToolConfirmDismiss(cb: (data: any) => void): void;
  approvePermission(id: string): Promise<any>; rejectPermission(id: string): Promise<any>; approveAlwaysPermission(id: string): Promise<any>;
  emailSendCode(email: string): Promise<any>; emailSendWelcome(email: string, displayName: string): Promise<any>;
  emailForgotPassword(email: string): Promise<any>;
  authUnlock(userId: string): Promise<any>; authLock(): Promise<any>;
  authGithubLogin(data: any): Promise<any>; authGithubLoginLoopback(): Promise<any>;
  authAdminResetPassword(email: string, newPassword: string): Promise<any>;
  authAdminConfirmUser(email: string): Promise<any>;
  authAdminCreateUser(email: string, password: string, displayName: string): Promise<any>;
  terminalCreate(type: string): Promise<any>; terminalWrite(id: string, input: string): Promise<any>;
  terminalRead(id: string, lines: number): Promise<any>; terminalKill(id: string): Promise<any>;
  flywheelStats(): Promise<Record<string, number>>;
  flywheelExport(format: string): Promise<any>;
  routerStats(problemType: string): Promise<any[]>;
  skillgraphEdges(limit: number): Promise<any[]>;
  skillgraphSimilar(goalText: string, limit: number): Promise<any[]>;
  skillsRegistry(): Promise<any[]>;
  skillRegistryList(): Promise<{ skills: any[]; categories: Record<string, any> }>;
  resultAnalyze(p: { text: string; type?: string }): Promise<any>;
  trainingList(): Promise<any[]>;
  trainingRun(id: string): Promise<any>;
  onTrainingLog(cb: (data: any) => void): void;
  onAgentSwitch(cb: (data: any) => void): void;
  securityAuditLog(): Promise<any[]>;
  securityVaultStatus(): Promise<any>;
  polarisModelList(): Promise<{ models: { name: string; location: string; size: number }[] }>;
  onModelInstallProgress(cb: (data: any) => void): void;
  skillgraphContext(goalText: string): Promise<string>;
}
interface Window { electronAPI?: PolarisAPI; }
