/**
 * Polaris Secret Vault
 * AES-256-GCM encrypted credentials. At runtime, decrypted into memory only.
 *
 * To update keys: run `node scripts/encrypt_secrets.js` with the new values.
 */
const { createCipheriv, createDecipheriv, randomBytes } = require('crypto');

// Derivation key — NOT the actual keys. This plus IV are the "lock" to the vault.
// An attacker would need BOTH the encrypted payloads AND this seed + IV to decrypt.
const VAULT_SEED = 'polaris_solver_bq7x_2026_agent_vault_k9';

// Encrypted payloads (generated by encrypting plaintext keys with the seed above)
// To regenerate, change the keys below and run: node -e "require('./electron/services/secrets').encryptAll()"
const VAULT = {
  deepseek_api_key: {
    iv:   'fa4e5cbd781fb312cd268902',
    data: '41b293f6f1d0a8df45b4e3c2b14dca455e0838f94af8a10ad5703cf04b9b662c74a4a5',
    tag:  'd101ce30ba9e7438dc032ec3bc48501c',
  },
  supabase_service_role: {
    iv:   '8797ad8b19e7f9b2802af892',
    data: '3f68051aa8ea7575f72d543ec54bf14a26815196f0d2c20fae624170673d737658ce56aae4d22fb162',
    tag:  'b3fe5b7d2193bc61eb86ef1f03b77787',
  },
  smtp_password: {
    iv:   'c96e407b330b539be3785782',
    data: '9b2be79ccf99e32c1acd7e0aec9bae94',
    tag:  'd561033d6141aa10bdb4cba3d7f90eeb',
  },
  github_client_secret: {
    iv:   '7039080ca78a42226d08f970',
    data: '115c5eeb6b5aee913d1089da9bc47bf5b06ef8aebb3ed999f17eadd37a1570644e4e17429d590584',
    tag:  '8581fdd5f9d920ea1daa572dcce819cb',
  },
};

/* ── Internal ────────────────────────────────────────── */
function deriveKey() {
  const { createHash } = require('crypto');
  return createHash('sha256').update(VAULT_SEED).digest();
}

function decrypt(entry) {
  const key = deriveKey();
  const decipher = createDecipheriv('aes-256-gcm', key, Buffer.from(entry.iv, 'hex'));
  decipher.setAuthTag(Buffer.from(entry.tag, 'hex'));
  let decrypted = decipher.update(entry.data, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  return decrypted;
}

function encrypt(plaintext) {
  const key = deriveKey();
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  let encrypted = cipher.update(plaintext, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return { iv: iv.toString('hex'), data: encrypted, tag: cipher.getAuthTag().toString('hex') };
}

/* ── Public API ─────────────────────────────────────── */
let _cache = null;

function getAll() {
  if (_cache) return _cache;
  _cache = {};
  for (const name of Object.keys(VAULT)) {
    try { _cache[name] = decrypt(VAULT[name]); }
    catch (e) { console.error(`[Vault] Failed to decrypt ${name}:`, e.message); _cache[name] = ''; }
  }
  return _cache;
}

function get(name) { return getAll()[name] || ''; }

// CLI regenerator: pass keys as env vars, outputs encrypted VAULT snippet
//   POLARIS_NEW_DEEPSEEK=sk-xxx POLARIS_NEW_SB_SECRET=sb_xxx POLARIS_NEW_SMTP=xxx node -e "require('./electron/services/secrets').encryptAll()"
function encryptAll() {
  var keys = {
    deepseek_api_key:    process.env.POLARIS_NEW_DEEPSEEK || process.argv[2] || '',
    supabase_service_role: process.env.POLARIS_NEW_SB_SECRET || process.argv[3] || '',
    smtp_password:        process.env.POLARIS_NEW_SMTP || process.argv[4] || '',
  };
  for (var name in keys) { if (!keys[name]) { console.error('Missing key for ' + name); return; } }
  console.log('// Paste into electron/services/secrets.js → VAULT object:\n');
  for (var _i = 0, _names = Object.keys(keys); _i < _names.length; _i++) {
    var n2 = _names[_i];
    var e2 = encrypt(keys[n2]);
    console.log('  ' + n2 + ': {');
    console.log('    iv:   \'' + e2.iv + '\',');
    console.log('    data: \'' + e2.data + '\',');
    console.log('    tag:  \'' + e2.tag + '\',');
    console.log('  },');
  }
  console.log('\n// Done.');
}

module.exports = { get, getAll, encryptAll };
