import React,{useState,useCallback,useRef,useEffect,useMemo}from'react';
import{useAppSelector,useAppDispatch}from'./store';
import{addMessage,editMessage,loadSessions as loadReducer,newSession as ns,setActiveSession,setStreaming,setStrategy,toggleSidebar,toggleSettings,setTheme,setLanguage,branchSession,addMemory,deleteSession}from'./store/chatSlice';
import type{ChatMessage,Strategy}from'./store/chatSlice';
import{saveSessions,loadSessions as loadStorage,deleteSessionStorage}from'./store/persist';
import SettingsPanel from'./components/SettingsPanel';

const S=['帮我写一封给投资人的项目介绍邮件','解释一下量子计算的基本原理','用 Python 写一个多线程下载器','帮我分析最近压力大的原因并给出建议'];

const WinBtns:React.FC=()=>(<div className="wb-row"><button onClick={()=>window.electronAPI?.minimize()}className="wb">{'─'}</button><button onClick={()=>window.electronAPI?.maximize()}className="wb">{'□'}</button><button onClick={()=>window.electronAPI?.close()}className="wb wb-close">{'✕'}</button></div>);

const SidebarView:React.FC<{onClose:()=>void}>=({onClose})=>{const d=useAppDispatch();const{sessions,activeSessionId}=useAppSelector(s=>s.chat);const[q,setQ]=useState('');const list=q?sessions.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())):sessions;const fmt=(t:number)=>{const dt=new Date(t);return dt.getMonth()+1+'/'+dt.getDate()};return(<div className="side"><div className="side-hd"><div className="side-logo">POLARIS</div><button onClick={onClose}className="side-cl">✕</button></div><button className="side-new"onClick={()=>d(ns())}>＋ 新对话</button><div className="side-srch"><input placeholder="搜索…"value={q}onChange={e=>setQ(e.target.value)}/></div><div className="side-list">{list.map(s=>(<div key={s.id}className={'side-it'+(s.id===activeSessionId?' on':'')}onClick={()=>d(setActiveSession(s.id))}><span className="side-dot"/><span className="side-nm">{s.name}</span><span className="side-dt">{fmt(s.createdAt)}</span><button className="side-del"onClick={e=>{e.stopPropagation();if(s.id!=='default'){d(deleteSession(s.id));deleteSessionStorage(s.id)}}}>×</button></div>))}</div><div className="side-ft">v0.9.0</div></div>);};

const MsgRow:React.FC<{msg:ChatMessage;isLast:boolean;onCopy:()=>void;onRegen:()=>void;onEdit:(v:string)=>void;onBranch:()=>void;copied:boolean}>=({msg,isLast,onCopy,onRegen,onEdit,onBranch,copied})=>{const[ed,setEd]=useState(false);const[v,setV]=useState(msg.content);if(msg.role==='user')return(<div className="msg-row u"><div className="ub">{msg.content}{msg.edited&&<span className="ed">(已编辑)</span>}</div></div>);return(<div className="msg-row"><div className="ab">{msg.routing&&<div className="rt"><span className="rt-i">{msg.routing.intent}</span><span className="rt-a">→</span>{msg.routing.models.map(m=><span key={m}className="rt-m">{m}</span>)}</div>}{ed?(<div><textarea className="ed-tx"value={v}onChange={e=>setV(e.target.value)}rows={6}/><div className="ed-bar"><button onClick={()=>{onEdit(v);setEd(false)}}className="ed-bt">保存</button><button onClick={()=>setEd(false)}className="ed-bt ed-c">取消</button></div></div>):<div dangerouslySetInnerHTML={{__html:md(msg.content)}}/>}<div className="ab-ft"><span className="ab-md">{msg.model||''}</span><span className="ab-act"><button onClick={onCopy}title="复制">{copied?'✓':'⎘'}</button>{isLast&&<><button onClick={onRegen}title="重新生成">↻</button><button onClick={onBranch}title="分支">⑂</button></>}<button onClick={()=>{setEd(true);setV(msg.content)}}title="编辑">✎</button></span></div></div></div>);};

const CmdPalette:React.FC<{onClose:()=>void}>=({onClose})=>{const d=useAppDispatch();const[q,setQ]=useState('');const cmds=useMemo(()=>{const all=[{id:'n',l:'新建对话',k:'Ctrl+N',a:()=>{d(ns());onClose()}},{id:'b',l:'切换侧边栏',k:'Ctrl+B',a:()=>{d(toggleSidebar());onClose()}},{id:',',l:'打开设置',k:'Ctrl+,',a:()=>{d(toggleSettings());onClose()}},{id:'e',l:'导出对话',k:'',a:()=>onClose()},{id:'t',l:'切换暗色主题',k:'',a:()=>{d(setTheme('dark'));onClose()}}];return q?all.filter(x=>x.l.toLowerCase().includes(q.toLowerCase())):all},[q,d,onClose]);useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[onClose]);return(<div className="cp-overlay"onClick={onClose}><div className="cp-box"onClick={e=>e.stopPropagation()}><input className="cp-in"autoFocus value={q}onChange={e=>setQ(e.target.value)}placeholder="输入命令…"/><div className="cp-list">{cmds.map(c=><div key={c.id}className="cp-item"onClick={c.a}><span>{c.l}</span><span className="cp-kbd">{c.k}</span></div>)}</div></div></div>);};

const App:React.FC=()=>{const d=useAppDispatch();const sc=useAppSelector(s=>s.chat);const{sessions,activeSessionId,streaming,strategy,sidebarOpen,settingsOpen,settings,contextTokens}=sc;const[inp,setInp]=useState('');const[thk,setThk]=useState('');const[st,setSt]=useState(false);const cr=useRef<HTMLDivElement>(null);const[fs,setFs]=useState<{u:string;n:string;t?:string}[]>([]);const[cid,setCid]=useState('');const[tpl,setTpl]=useState(false);const[web,setWeb]=useState(false);const[drag,setDrag]=useState(false);const[cmd,setCmd]=useState(false);const[desk,setDesk]=useState(false);const[da,setDa]=useState('');const[doing,setDoing]=useState(false);const[rips,setRips]=useState<{id:number;x:number;y:number}[]>([]);const stop=useRef(false);const ir=useRef<HTMLTextAreaElement>(null);const act=sessions.find(s=>s.id===activeSessionId);

// Theme init
useEffect(()=>{document.documentElement.setAttribute('data-theme',settings.theme)},[settings.theme]);
// Lang + load saved
useEffect(()=>{d(setLanguage('zh-CN'));const saved=loadStorage();if(saved.length>0)d(loadReducer(saved))},[d]);
// Auto-save
useEffect(()=>{if(sessions.length>0){const t=setTimeout(()=>saveSessions(sessions),500);return()=>clearTimeout(t)}},[sessions]);
// Scroll
useEffect(()=>{cr.current?.scrollTo({top:cr.current.scrollHeight,behavior:'smooth'})},[act?.messages,thk]);
// Ripples
useEffect(()=>{if(rips.length>0){const t=setTimeout(()=>setRips([]),700);return()=>clearTimeout(t)}},[rips]);
// Keys
useEffect(()=>{const h=(e:KeyboardEvent)=>{
  if((e.ctrlKey||e.metaKey)&&e.key==='p'){e.preventDefault();setCmd(true)}
  if(e.key==='Escape'){stop.current=true;d(setStreaming(false));setThk('');setCmd(false)}
  if((e.ctrlKey||e.metaKey)&&e.key==='n'){e.preventDefault();d(ns())}
  if((e.ctrlKey||e.metaKey)&&e.key==='b'){e.preventDefault();d(toggleSidebar())}
  if((e.ctrlKey||e.metaKey)&&e.key===','){e.preventDefault();d(toggleSettings())}
};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[d]);

const execDesk=useCallback(async(a:any)=>{if(!a)return;const api=window.electronAPI;if(!api)return;switch(a.action){case'open_browser':if(a.url)api.desktopOpenBrowser(a.url);break;case'click':if(a.x!==undefined&&a.y!==undefined){api.desktopClickMouse(a.x,a.y,a.button||'left');setRips([{id:Date.now(),x:a.x,y:a.y}])}break;case'type':if(a.text)api.desktopTypeText(a.text);break;case'press_key':if(a.key)api.desktopPressKey(a.key);break;case'hotkey':if(a.combo)api.desktopHotkey(a.combo);break;case'run_command':if(a.command)await api.desktopRunCommand(a.command);break;case'wait':if(a.ms)await new Promise(r=>setTimeout(r,a.ms));break;case'write_file':if(a.path&&a.content)api.desktopWriteFile(a.path,a.content);break}},[]);

const query=useCallback(async(t:string,rgn?:boolean)=>{if(!t||streaming)return;stop.current=false;const img=fs.filter(f=>f.u.startsWith('data:image')).map(f=>f.u);const txt=fs.filter(f=>f.t).map(f=>'[文件: '+f.n+']\n'+f.t).join('\n');setInp('');setFs([]);if(!rgn){d(addMessage({sessionId:activeSessionId!,message:{id:'u'+Date.now(),role:'user',content:t,timestamp:Date.now()}}))}d(setStreaming(true));setThk('分析中…');try{let ctx=t;if(txt)ctx+='\n\n'+txt;if(web){try{const{webSearch}=await import('./utils/search');const r=await webSearch(t,settings.apiKeys.serper);if(r.length>0&&!r[0].title.includes('未配置'))ctx+='\n[搜索]\n'+r.map(x=>'- '+x.title+': '+x.snippet).join('\n')}catch{}}const res=await(window.electronAPI?window.electronAPI.query({text:ctx,strategy,images:img.length?img:undefined}):Promise.reject(new Error('API未就绪')));if(stop.current)return;setThk(res.routing.selected_models.join(', '));const cnt=res.responses.length===1?res.responses[0].content||'(空)':res.responses.map(r=>'**▸ '+r.model_id+'**\n\n'+(r.content||'')).join('\n\n---\n\n');if(settings.memory.enabled&&cnt.length>50)d(addMemory({key:t.slice(0,40),value:cnt.slice(0,200)}));d(addMessage({sessionId:activeSessionId!,message:{id:'a'+Date.now(),role:'assistant',content:cnt,timestamp:Date.now(),model:res.routing.selected_models.join(', '),routing:{intent:res.routing.top_intent,models:res.routing.selected_models,rationale:res.routing.rationale}}}));try{window.electronAPI?.notify({title:'Polaris',body:'回复已生成'})}catch{}}catch(e:any){if(!stop.current)d(addMessage({sessionId:activeSessionId!,message:{id:'e'+Date.now(),role:'assistant',content:'出错: '+(e.message||'API未连接'),timestamp:Date.now()}}))}d(setStreaming(false));setThk('')},[streaming,strategy,activeSessionId,d,fs,web,settings]);

const send=()=>{const t=inp.trim();if(!t||streaming||doing)return;const isDesk=t.includes('打开')||t.includes('帮我搜')||t.includes('桌面');if(isDesk){setInp('');setDesk(true);setDoing(true);setDa('正在截图…');(async()=>{try{const api=window.electronAPI;if(!api)throw new Error('桌面API未就绪');const ss=await api.desktopScreenshot();setDa('分析中…');const st1=await api.desktopAgentStep({goal:t,screenshot:ss||'',history:''});if(st1?.action&&!stop.current){setDa(st1.action.reason||'执行中');await execDesk(st1.action);d(addMessage({sessionId:activeSessionId!,message:{id:'a'+Date.now(),role:'assistant',content:'**桌面操作:** '+(st1.action.reason||t),timestamp:Date.now(),model:'desktop-agent',routing:{intent:'desktop',models:['desktop-agent'],rationale:st1.action.action}}}))}setDa('✓ 完成');setTimeout(()=>{setDesk(false);setDa('')},2500)}catch(e:any){setDa('✗ '+(e.message||''));d(addMessage({sessionId:activeSessionId!,message:{id:'e'+Date.now(),role:'assistant',content:'桌面操作出错: '+(e.message||''),timestamp:Date.now()}}));setTimeout(()=>{setDesk(false);setDa('')},3000)}setDoing(false)})()}else{query(t)}}
const cp=(c:string)=>{navigator.clipboard.writeText(c).catch(()=>{});setCid(c.slice(0,20));setTimeout(()=>setCid(''),1500)}
const rg=()=>{if(!act||act.messages.length<2)return;const u=[...act.messages].reverse().find(m=>m.role==='user');if(u)query(u.content,true)}
const em=(v:string)=>{if(!act)return;const a=[...act.messages].reverse().find(m=>m.role==='assistant');if(a)d(editMessage({sessionId:act.id,messageId:a.id,content:v}))}
const br=()=>{if(!act||act.messages.length<2)return;const u=[...act.messages].reverse().find(m=>m.role==='user');if(u)d(branchSession({sourceSessionId:act.id,upToMessageId:u.id}))}
const ex=()=>{if(!act||act.messages.length===0)return;const md=act.messages.map(m=>`### ${m.role==='user'?'用户':'AI'}\n\n${m.content}\n`).join('\n---\n');const b=new Blob([md],{type:'text/markdown'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(act.name||'对话')+'.md';a.click()}
const dp=async(e:React.DragEvent)=>{e.preventDefault();setDrag(false);for(const f of Array.from(e.dataTransfer.files)){if(f.type.startsWith('image/')){const r=new FileReader();r.onload=()=>setFs(p=>[...p,{u:r.result as string,n:f.name}]);r.readAsDataURL(f);continue}try{const t=await f.text();setFs(p=>[...p,{u:'',n:f.name,t:t.slice(0,5000)}])}catch{}}}
const pct=contextTokens.total>0?Math.min(Math.round(contextTokens.used/Math.max(contextTokens.total,1)*100),100):0;

return(<div className="app"onDragOver={e=>{e.preventDefault();setDrag(true)}}onDragLeave={()=>setDrag(false)}onDrop={dp}>
  <div className="tb"><div className="tb-l"><span className="tb-lg">✦ Polaris</span><div className="tb-tk"><div className="tb-tk-f"style={{width:pct+'%',background:pct>80?'var(--red)':pct>50?'var(--accent)':'var(--green)'}}/></div></div><div className="tb-r"><button className="tb-btn"onClick={()=>d(toggleSidebar())}title="侧边栏 Ctrl+B">☰</button><button className="tb-btn"onClick={()=>setCmd(true)}title="命令面板 Ctrl+P">⌘</button><button className="tb-btn"onClick={ex}title="导出">↓</button><button className="tb-btn"onClick={()=>d(toggleSettings())}title="设置 Ctrl+,">⚙</button><WinBtns/></div></div>
  {drag&&<div className="dov"><div className="doz"><p>拖拽文件到此处上传</p></div></div>}
  {fs.length>0&&<div className="fb">{fs.map((f,i)=><div key={i}className="fc"><span>{f.n}</span><button onClick={()=>setFs(p=>p.filter((_,j)=>j!==i))}className="fcx">✕</button></div>)}</div>}
  {desk&&<div className="desk-overlay"><div className="desk-banner"><div className="desk-dot"/><span>{da}</span></div></div>}
  {rips.map(r=><div key={r.id}className="click-ripple"style={{left:r.x-15,top:r.y-15}}/>)}
  <div className="body">{sidebarOpen&&<SidebarView onClose={()=>d(toggleSidebar())}/>}<div className="main">
    <div className="chat"ref={cr}>{(!act||act.messages.length===0)?(<div className="empty"><div className="elg">✦</div><h2>有什么我可以帮你的？</h2><p className="eh">Ctrl+P 命令面板 · Ctrl+N 新建 · 拖拽文件上传</p><div className="esg">{S.map((s,i)=><button key={i}className="es"onClick={()=>{setInp(s);send()}}>{s}</button>)}</div></div>):(act.messages.map((m,i)=><MsgRow key={m.id}msg={m}isLast={i===act.messages.length-1}onCopy={()=>cp(m.content)}onRegen={rg}onEdit={em}onBranch={br}copied={cid===m.content.slice(0,20)}/>))}{thk&&<div className="tm"><div className="tm-d"/><span>{thk}</span></div>}</div>
    <div className="ia">
      {tpl&&<div className="tpp">{settings.promptTemplates.map(t=><button key={t.id}className="tpi"onClick={()=>{setInp(t.content);setTpl(false);ir.current?.focus()}}><span className="tpn">{t.name}</span><span className="tpc">{t.category}</span></button>)}</div>}
      <div className="irr">
        <button className="vo-btn"onClick={async()=>{try{const{startListening}=await import('./utils/voice');startListening('zh-CN',(t:string)=>{setInp(p=>p+t)},()=>{})}catch{}}}disabled={streaming}title="语音">🎤</button>
        <textarea ref={ir}className="itx"value={inp}onChange={e=>{setInp(e.target.value);e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,150)+'px'}}onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}placeholder="问点什么…  Ctrl+P 命令面板 · 拖拽文件上传"rows={1}disabled={streaming||doing}/>
        {streaming?<button className="ib-st"onClick={()=>{stop.current=true;d(setStreaming(false));setThk('')}}title="停止 Esc">■</button>:<button className="ib-sd"onClick={send}disabled={doing||!inp.trim()}>↑</button>}
      </div>
      <div className="io"><div style={{display:'flex',gap:6}}><div className="sp"onMouseEnter={()=>setSt(true)}onMouseLeave={()=>setSt(false)}><span className="sl">{{best_quality:'✦ 优质',cost_optimized:'◆ 省钱',ensemble:'◈ 协同'}[strategy]}</span>{st&&<div className="sd">{(['best_quality','cost_optimized','ensemble']as Strategy[]).map(s=><div key={s}className={'si'+(strategy===s?' so':'')}onClick={()=>{d(setStrategy(s));setSt(false)}}>{{best_quality:'✦ 优质',cost_optimized:'◆ 省钱',ensemble:'◈ 协同'}[s]}</div>)}</div>}</div><button className={'oc'+(web?' on':'')}onClick={()=>setWeb(!web)}>🌐 {web?'ON':'OFF'}</button><button className="oc"onClick={()=>setTpl(!tpl)}>📋 模板</button></div><span className="ih">Enter 发送 · Shift+Enter 换行</span></div></div>
  </div></div>
  {settingsOpen&&<SettingsPanel/>}{cmd&&<CmdPalette onClose={()=>setCmd(false)}/>}
</div>)};

function md(t:string):string{let h=t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');h=h.replace(/```mermaid\n([\s\S]*?)```/g,(_,c:string)=>'<div class="mdb">'+c.trim()+'</div>');h=h.replace(/```(\w*)\n([\s\S]*?)```/g,(_,l:string,c:string)=>'<pre class="cb"><div class="cb-l">'+(l||'text')+'</div><code>'+hl(c.trim(),l)+'</code></pre>');h=h.replace(/`([^`]+)`/g,'<code>$1</code>');h=h.replace(/\*\*\*(.+?)\*\*\*/g,'<strong><em>$1</em></strong>');h=h.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');h=h.replace(/\*(.+?)\*/g,'<em>$1</em>');h=h.replace(/\$\$(.+?)\$\$/g,(_,f:string)=>'<div class="lx">'+f+'</div>');h=h.replace(/\$(.+?)\$/g,(_,f:string)=>'<span class="li">'+f+'</span>');h=h.replace(/^### (.+)/gm,'<h3>$1</h3>');h=h.replace(/^## (.+)/gm,'<h2>$1</h2>');h=h.replace(/^# (.+)/gm,'<h1>$1</h1>');h=h.replace(/^[-*] (.+)/gm,'<li>$1</li>');h=h.replace(/((?:<li>.*<\/li>\n?)+)/g,'<ul>$1</ul>');h=h.replace(/\n\n/g,'</p><p>');h=h.replace(/\n/g,'<br/>');return'<p>'+h+'</p>'}
function hl(c:string,l:string):string{const kw:Record<string,string[]>={js:['const','let','var','function','return','if','else','for','while','class','export','import','async','await','try','catch','throw','new','this'],py:['def','return','if','elif','else','for','while','class','import','from','async','await','try','except','raise','with','as','None','True','False'],ts:['const','let','var','function','return','if','else','for','while','class','export','import','async','await','try','catch','throw','new','this','interface','type','extends']};const w=kw[l]||[];let o=c;w.forEach(x=>{o=o.replace(new RegExp('\\b'+x+'\\b','g'),'<span class="hk">'+x+'</span>')});o=o.replace(/(\".*?\")/g,'<span class="hs">$1</span>');o=o.replace(/(\'.*?\')/g,'<span class="hs">$1</span>');o=o.replace(/(\/\/.*)/g,'<span class="hc">$1</span>');o=o.replace(/(\d+)/g,'<span class="hn">$1</span>');return o}
export default App;
