import React,{useState,useCallback,useRef,useEffect,useMemo}from'react';
import{useAppSelector,useAppDispatch}from'./store';
import{addMessage,editMessage,loadSessions as lr,newSession as ns,setActiveSession,setStreaming,setStrategy,toggleSidebar,toggleSettings,setTheme,setLanguage,branchSession,addMemory}from'./store/chatSlice';
import type{ChatMessage,Strategy}from'./store/chatSlice';
import{saveSessions,loadSessions as ld}from'./store/persist';
import SettingsPanel from'./components/SettingsPanel';
import SidebarFull from'./components/SidebarFull';

const S=['帮我写一封给投资人的项目介绍邮件','解释一下量子计算的基本原理','用 Python 写一个多线程下载器','帮我分析最近压力大的原因并给出建议'];
const WinBtns:React.FC=()=>(<div className="wb-row"><button onClick={()=>window.electronAPI?.minimize()}className="wb">{'─'}</button><button onClick={()=>window.electronAPI?.maximize()}className="wb">{'□'}</button><button onClick={()=>window.electronAPI?.close()}className="wb wb-close">{'✕'}</button></div>);
const MsgRow:React.FC<{msg:ChatMessage;isLast:boolean;onCopy:()=>void;onRegen:()=>void;onEdit:(v:string)=>void;onBranch:()=>void;cid:boolean;streaming?:string}>=({msg,isLast,onCopy,onRegen,onEdit,onBranch,cid,streaming})=>{const[ed,setEd]=useState(false);const[v,setV]=useState(msg.content);if(msg.role==='user')return(<div className="msg-row u"><div className="ub">{msg.content}{msg.edited&&<span className="ed">(已编辑)</span>}</div></div>);const displayContent = isLast && streaming !== undefined ? (msg.content + (streaming ? '<span class="cur-blink"></span>' + streaming : '')) : msg.content;return(<div className="msg-row"><div className="ab">{msg.routing&&<div className="rt"><span className="rt-i">{msg.routing.intent}</span><span className="rt-a">→</span>{msg.routing.models.map(m=><span key={m}className="rt-m">{m}</span>)}</div>}{ed?(<div><textarea className="ed-tx"value={v}onChange={e=>setV(e.target.value)}rows={6}/><div className="ed-bar"><button onClick={()=>{onEdit(v);setEd(false)}}className="ed-bt">保存</button><button onClick={()=>setEd(false)}className="ed-bt ed-c">取消</button></div></div>):<div dangerouslySetInnerHTML={{__html:md(displayContent)+(isLast&&streaming!==undefined&&streaming?'' : '')+(isLast&&streaming?'<span class="cur-blink"></span>':'')}}/>}<div className="ab-ft"><span className="ab-md">{msg.model||''}</span><span className="ab-act"><button onClick={onCopy}title="复制">{cid?'✓':'⎘'}</button>{isLast&&<><button onClick={onRegen}title="重新生成">↻</button><button onClick={onBranch}title="分支">⑂</button></>}<button onClick={()=>{setEd(true);setV(msg.content)}}title="编辑">✎</button></span></div></div></div>);};
const CmdPalette:React.FC<{onClose:()=>void}>=({onClose})=>{const d=useAppDispatch();const[q,setQ]=useState('');const cmds=useMemo(()=>{const all=[{id:'n',l:'新建对话',k:'Ctrl+N',a:()=>{d(ns());onClose()}},{id:'b',l:'侧边栏',k:'Ctrl+B',a:()=>{d(toggleSidebar());onClose()}},{id:',',l:'设置',k:'Ctrl+,',a:()=>{d(toggleSettings());onClose()}},{id:'t',l:'暗色主题',k:'',a:()=>{d(setTheme('dark'));onClose()}}];return q?all.filter(x=>x.l.toLowerCase().includes(q.toLowerCase())):all},[q,d,onClose]);return(<div className="cp-overlay"onClick={onClose}><div className="cp-box"onClick={e=>e.stopPropagation()}><input className="cp-in"autoFocus value={q}onChange={e=>setQ(e.target.value)}placeholder="输入命令…"/><div className="cp-list">{cmds.map(c=><div key={c.id}className="cp-item"onClick={c.a}><span>{c.l}</span><span className="cp-kbd">{c.k}</span></div>)}</div></div></div>);};

// Intervention card inline component
const IntCard:React.FC<{card:any;onConfirm:(c:any)=>void;onDismiss:(c:any)=>void}>=({card,onConfirm,onDismiss})=>(<div className="int-card"style={{borderColor:card.level===3?'var(--red)':card.level===2?'var(--accent)':'var(--cyan)'}}><div className="int-hdr"><span className="int-title">{card.title}</span><span className="int-lvl">L{card.level}</span></div><p className="int-body">{card.body}</p>{card.actions&&<div className="int-acts">{card.actions.map((a:any)=><button key={a.label}className="int-btn"onClick={()=>a.action==='dismiss'?onDismiss(card):onConfirm(card)}>{a.label}</button>)}</div>}</div>);

// Plan card
const PlanCard:React.FC<{plan:any;onConfirm:()=>void;onReject:()=>void;progress?:any}>=({plan,onConfirm,onReject,progress})=>(<div className="plan-card"><div className="plan-hdr"><span className="plan-title">执行计划</span></div><p className="plan-req">{plan.request?.slice(0,80)}</p><div className="plan-steps">{plan.steps?.map((s:any)=><div key={s.id}className={`plan-step${progress&&progress.step===s.id?' active':''}${progress&&progress.type==='step_done'&&progress.step===s.id?' done':''}`}><span className="ps-check">{progress&&progress.step===s.id&&progress.type==='step_done'?'✓':(progress&&progress.step===s.id?'●':'○')}</span><span>{s.description}</span><span className="ps-risk"style={{color:s.risk==='high'?'var(--red)':s.risk==='medium'?'var(--accent)':''}}>{s.risk}</span></div>)}</div><div className="plan-acts">{!progress?<><button className="plan-btn plan-yes"onClick={onConfirm}>确认执行</button><button className="plan-btn plan-no"onClick={onReject}>取消</button></>:<button className="plan-btn plan-no"onClick={onReject}>停止</button>}</div></div>);

const App:React.FC=()=>{const d=useAppDispatch();const sc=useAppSelector(s=>s.chat);const{sessions,activeSessionId,streaming,strategy,sidebarOpen,settingsOpen,settings,contextTokens}=sc;const[inp,setInp]=useState('');const[thk,setThk]=useState('');const[st,setSt]=useState(false);const cr=useRef<HTMLDivElement>(null);const[fs,setFs]=useState<{u:string;n:string;t?:string}[]>([]);const[cid,setCid]=useState('');const[tpl,setTpl]=useState(false);const[web,setWeb]=useState(false);const[drag,setDrag]=useState(false);const[cmd,setCmd]=useState(false);const[doing,setDoing]=useState(false);const stop=useRef(false);const ir=useRef<HTMLTextAreaElement>(null);const act=sessions.find(s=>s.id===activeSessionId);
// New state for streaming + interventions + plans
const[strmText,setStrmText]=useState('');const[strmModel,setStrmModel]=useState('');
const[interventions,setInterventions]=useState<any[]>([]);
const[plan,setPlan]=useState<any>(null);const[planProg,setPlanProg]=useState<any>(null);const[planId,setPlanId]=useState('');

useEffect(()=>{document.documentElement.setAttribute('data-theme',settings.theme)},[settings.theme]);
useEffect(()=>{d(setLanguage('zh-CN'));const s=ld();if(s.length>0)d(lr(s))},[d]);
useEffect(()=>{if(sessions.length>0){const t=setTimeout(()=>saveSessions(sessions),500);return()=>clearTimeout(t)}},[sessions]);
useEffect(()=>{cr.current?.scrollTo({top:cr.current.scrollHeight,behavior:'smooth'})},[act?.messages,thk,strmText,interventions]);
useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='p'){e.preventDefault();setCmd(true)}if(e.key==='Escape'){stop.current=true;d(setStreaming(false));setThk('');setCmd(false);setStrmText('')}if((e.ctrlKey||e.metaKey)&&e.key==='n'){e.preventDefault();d(ns())}if((e.ctrlKey||e.metaKey)&&e.key==='b'){e.preventDefault();d(toggleSidebar())}if((e.ctrlKey||e.metaKey)&&e.key===','){e.preventDefault();d(toggleSettings())}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[d]);
// System monitor init + keyboard activity tracking
useEffect(()=>{const api=window.electronAPI;if(!api)return;api.monitorStart();let pressCount=0;let delCount=0;let lastKb=Date.now();const onKb=()=>{pressCount++;lastKb=Date.now();if(pressCount%50===0)api.monitorUpdate({count:pressCount,delete:delCount,lastPress:lastKb,window:document.title})};const onDel=(e:KeyboardEvent)=>{if(e.key==='Backspace'||e.key==='Delete')delCount++};window.addEventListener('keydown',onKb);window.addEventListener('keydown',onDel);api.onIntervention((card:any)=>setInterventions(p=>[...p.slice(-5),card]));api.onPlanProgress((data:any)=>setPlanProg(data));return()=>{window.removeEventListener('keydown',onKb);window.removeEventListener('keydown',onDel)}},[]);

const query=useCallback(async(t:string,rgn?:boolean)=>{if(!t||streaming)return;stop.current=false;const imgs=fs.filter(f=>f.u.startsWith('data:image')).map(f=>f.u);const txts=fs.filter(f=>f.t).map(f=>'[文件: '+f.n+']\n'+f.t).join('\n');setInp('');setFs([]);if(!rgn){d(addMessage({sessionId:activeSessionId!,message:{id:'u'+Date.now(),role:'user',content:t,timestamp:Date.now()}}))}d(setStreaming(true));setThk('分析中…');setStrmText('');setStrmModel('');
// Desktop automation? → Use planner
if(t.includes('帮')&&/[打开|执行|整理|搜索|移动|复制|删除|运行]/.test(t)&&!t.includes('写')&&!t.includes('代码')&&!t.includes('翻译')&&!t.includes('分析')&&!t.includes('解释')){try{const api=window.electronAPI;if(!api)throw new Error('API未就绪');const p=await api.plannerGenerate(t);setPlan(p);setPlanId(p.id);d(setStreaming(false));setThk('');return}catch(e){/* fall through to AI */}}
try{let ctx=t;if(txts)ctx+='\n\n'+txts;if(web){try{const{webSearch}=await import('./utils/search');const r=await webSearch(t,settings.apiKeys.serper);if(r.length>0&&!r[0].title.includes('未配置'))ctx+='\n[搜索]\n'+r.map(x=>'- '+x.title+': '+x.snippet).join('\n')}catch{}}
const api=window.electronAPI;if(!api)throw new Error('API未就绪');
// Use streaming if available
try{const streamRes=await api.queryStream({text:ctx,strategy,images:imgs.length?imgs:undefined,apiKeys:settings.apiKeys});
if(stop.current)return;setThk(streamRes.routing?.selected_models?.join(', ')||'');
let cnt=streamRes.responses?.map((r:any)=>r.content||'').join('\n\n---\n\n')||'';
if(streamRes.workflow_steps?.length)cnt='**[工作流 · '+streamRes.routing?.rationale+']**\n\n'+streamRes.workflow_steps.map((s:any)=>'> ✓ '+s.id+': '+s.agent+' — '+((s.summary||'').slice(0,100))).join('\n')+'\n\n---\n\n'+cnt;
if(streamRes.ensemble?.disagreements?.length)cnt+='\n\n⚠️ **合奏分歧:**\n'+streamRes.ensemble.disagreements.map((d:any)=>'> ['+d.type+'] '+d.model_a+' vs '+d.model_b).join('\n');
if(settings.memory.enabled&&cnt.length>50)d(addMemory({key:t.slice(0,40),value:cnt.slice(0,200)}));
d(addMessage({sessionId:activeSessionId!,message:{id:'a'+Date.now(),role:'assistant',content:cnt,timestamp:Date.now(),model:streamRes.routing?.selected_models?.join(', ')||'',routing:{intent:streamRes.routing?.top_intent,models:streamRes.routing?.selected_models||[],rationale:streamRes.routing?.rationale||''}}}));
}catch{
// Fallback to non-streaming
const res=await api.query({text:ctx,strategy,images:imgs.length?imgs:undefined,apiKeys:settings.apiKeys});
if(stop.current)return;setThk(res.routing.selected_models.join(', '));let cnt=res.responses.map((r:any)=>r.content||'').join('\n\n---\n\n');if(res.workflow_steps?.length)cnt='**[工作流 · '+res.routing.rationale+']**\n\n'+res.workflow_steps.map((s:any)=>'> ✓ '+s.id+': '+s.agent+' — '+((s.summary||'').slice(0,100))).join('\n')+'\n\n---\n\n'+cnt;if(res.ensemble?.disagreements?.length)cnt+='\n\n⚠️ **合奏分歧 ('+res.ensemble.consensus_level+'):**\n'+res.ensemble.disagreements.map((d:any)=>'> ['+d.type+'] '+d.model_a+' vs '+d.model_b+' — '+(d.a_excerpt||'').slice(0,100)).join('\n');if(res.expert_responses?.length)cnt+='\n\n**协同引擎 — 专家分析:**\n'+res.expert_responses.map((e:any)=>'> **['+e.role+']** '+e.modelDisplay+': '+(e.content||'').slice(0,200)).join('\n\n');if(settings.memory.enabled&&cnt.length>50)d(addMemory({key:t.slice(0,40),value:cnt.slice(0,200)}));d(addMessage({sessionId:activeSessionId!,message:{id:'a'+Date.now(),role:'assistant',content:cnt,timestamp:Date.now(),model:res.routing.selected_models.join(', '),routing:{intent:res.routing.top_intent,models:res.routing.selected_models,rationale:res.routing.rationale}}}));
}}catch(e:any){if(!stop.current)d(addMessage({sessionId:activeSessionId!,message:{id:'e'+Date.now(),role:'assistant',content:'出错: '+(e.message||'API未连接'),timestamp:Date.now()}}))}d(setStreaming(false));setThk('');setStrmText('')},[streaming,strategy,activeSessionId,d,fs,web,settings]);

const confirmPlan=async()=>{if(!planId)return;const api=window.electronAPI;if(!api)return;setThk('执行中…');d(setStreaming(true));try{await api.plannerExecute(planId);setPlan(null);setPlanId('');setPlanProg(null);d(addMessage({sessionId:activeSessionId!,message:{id:'p'+Date.now(),role:'assistant',content:'计划执行完毕 ✓',timestamp:Date.now(),model:'Polaris Planner'}}))}catch(e:any){d(addMessage({sessionId:activeSessionId!,message:{id:'e'+Date.now(),role:'assistant',content:'执行失败: '+e.message,timestamp:Date.now()}}))}d(setStreaming(false));setThk('')};
const rejectPlan=async()=>{const api=window.electronAPI;if(!api)return;await api.plannerReject(planId);setPlan(null);setPlanId('');setPlanProg(null)};
const confInt=(card:any)=>{const api=window.electronAPI;if(api&&card.eventKey)api.monitorFeedback({eventKey:card.eventKey,accepted:true});setInterventions(p=>p.filter(c=>c.timestamp!==card.timestamp))};
const dismInt=(card:any)=>{const api=window.electronAPI;if(api&&card.eventKey)api.monitorFeedback({eventKey:card.eventKey,accepted:false});setInterventions(p=>p.filter(c=>c.timestamp!==card.timestamp))};
const useTpl=(prompt:string)=>{d(ns());setTimeout(()=>{setInp(prompt);ir.current?.focus();},100)}
const send=()=>{const t=inp.trim();if(!t||streaming||doing)return;query(t)}
const cp=(c:string)=>{navigator.clipboard.writeText(c).catch(()=>{});setCid(c.slice(0,20));setTimeout(()=>setCid(''),1500)}
const rg=()=>{if(!act||act.messages.length<2)return;const u=[...act.messages].reverse().find(m=>m.role==='user');if(u)query(u.content,true)}
const em=(v:string)=>{if(!act)return;const a=[...act.messages].reverse().find(m=>m.role==='assistant');if(a)d(editMessage({sessionId:act.id,messageId:a.id,content:v}))}
const br=()=>{if(!act||act.messages.length<2)return;const u=[...act.messages].reverse().find(m=>m.role==='user');if(u)d(branchSession({sourceSessionId:act.id,upToMessageId:u.id}))}
const ex=()=>{if(!act||act.messages.length===0)return;const md2=act.messages.map(m=>'### '+(m.role==='user'?'用户':'AI')+'\n\n'+m.content+'\n').join('\n---\n');const b=new Blob([md2],{type:'text/markdown'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(act.name||'对话')+'.md';a.click()}
const dp=async(e:React.DragEvent)=>{e.preventDefault();setDrag(false);for(const f of Array.from(e.dataTransfer.files)){if(f.type.startsWith('image/')){const r=new FileReader();r.onload=()=>setFs(p=>[...p,{u:r.result as string,n:f.name}]);r.readAsDataURL(f);continue}try{const t=await f.text();setFs(p=>[...p,{u:'',n:f.name,t:t.slice(0,5000)}])}catch{}}}
const pct=contextTokens.total>0?Math.min(Math.round(contextTokens.used/Math.max(contextTokens.total,1)*100),100):0;

return(<div className="app"onDragOver={e=>{e.preventDefault();setDrag(true)}}onDragLeave={()=>setDrag(false)}onDrop={dp}>
  <div className="tb"><div className="tb-l"><span className="tb-lg">✦ Polaris</span><div className="tb-tk"><div className="tb-tk-f"style={{width:pct+'%',background:pct>80?'var(--red)':pct>50?'var(--accent)':'var(--green)'}}/></div></div><div className="tb-r"><button className="tb-btn"onClick={()=>d(toggleSidebar())}title="侧边栏 Ctrl+B">☰</button><button className="tb-btn"onClick={()=>setCmd(true)}title="命令面板 Ctrl+P">⌘</button><button className="tb-btn"onClick={ex}title="导出">↓</button><button className="tb-btn"onClick={()=>d(toggleSettings())}title="设置 Ctrl+,">⚙</button><WinBtns/></div></div>
  {drag&&<div className="dov"><div className="doz"><p>拖拽文件到此处上传</p></div></div>}
  {fs.length>0&&<div className="fb">{fs.map((f,i)=><div key={i}className="fc"><span>{f.n}</span><button onClick={()=>setFs(p=>p.filter((_,j)=>j!==i))}className="fcx">✕</button></div>)}</div>}
  <div className="body">{sidebarOpen&&<SidebarFull onClose={()=>d(toggleSidebar())} onUseTemplate={useTpl}/>}<div className="main">
    <div className="chat"ref={cr}>
      {/* Interventions pinned at top */}
      {interventions.map(c=><IntCard key={c.timestamp}card={c}onConfirm={confInt}onDismiss={dismInt}/>)}
      {/* Plan card */}
      {plan&&<PlanCard plan={plan}onConfirm={confirmPlan}onReject={rejectPlan}progress={planProg}/>}
      {(!act||act.messages.length===0)?(<div className="empty"><div className="elg">✦</div><h2>有什么我可以帮你的？</h2><p className="eh">Ctrl+P 命令面板 · Ctrl+N 新建 · 拖拽文件上传 · 语音/文本双输入</p><div className="esg">{S.map((s,i)=><button key={i}className="es"onClick={()=>{setInp(s);send()}}>{s}</button>)}</div></div>):(act.messages.map((m,i)=><MsgRow key={m.id}msg={m}isLast={i===act.messages.length-1}onCopy={()=>cp(m.content)}onRegen={rg}onEdit={em}onBranch={br}cid={cid===m.content.slice(0,20)}streaming={i===act.messages.length-1&&streaming?strmText:undefined}/>))}{thk&&!strmText&&<div className="tm"><div className="tm-d"/><span>{thk}</span></div>}</div>
    <div className="ia">{tpl&&<div className="tpp">{settings.promptTemplates.map(t=><button key={t.id}className="tpi"onClick={()=>{setInp(t.content);setTpl(false);ir.current?.focus()}}><span className="tpn">{t.name}</span><span className="tpc">{t.category}</span></button>)}</div>}
      <div className="irr"><button className="vo-btn"onClick={async()=>{try{const{startListening}=await import('./utils/voice');startListening('zh-CN',(t:string)=>{setInp(p=>p+t)},()=>{})}catch{}}}disabled={streaming}title="语音">🎤</button>
      <textarea ref={ir}className="itx"value={inp}onChange={e=>{setInp(e.target.value);e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,150)+'px'}}onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}placeholder="问点什么…  Ctrl+P 命令面板 · 拖拽文件上传"rows={1}disabled={streaming||doing}/>
      {streaming?<button className="ib-st"onClick={()=>{stop.current=true;d(setStreaming(false));setThk('');setStrmText('')}}title="停止 Esc">■</button>:<button className="ib-sd"onClick={send}disabled={doing||!inp.trim()}>↑</button>}</div>
      <div className="io"><div style={{display:'flex',gap:6}}><div className="sp"onMouseEnter={()=>setSt(true)}onMouseLeave={()=>setSt(false)}><span className="sl">{{best_quality:'✦ 优质',cost_optimized:'◆ 省钱',ensemble:'◈ 协同'}[strategy]}</span>{st&&<div className="sd">{(['best_quality','cost_optimized','ensemble']as Strategy[]).map(s=><div key={s}className={'si'+(strategy===s?' so':'')}onClick={()=>{d(setStrategy(s));setSt(false)}}>{{best_quality:'✦ 优质',cost_optimized:'◆ 省钱',ensemble:'◈ 协同'}[s]}</div>)}</div>}</div><button className={'oc'+(web?' on':'')}onClick={()=>setWeb(!web)}>🌐 {web?'ON':'OFF'}</button><button className="oc"onClick={()=>setTpl(!tpl)}>📋 模板</button></div><span className="ih">Enter 发送 · Shift+Enter 换行</span></div></div>
  </div></div>
  {settingsOpen&&<SettingsPanel/>}{cmd&&<CmdPalette onClose={()=>setCmd(false)}/>}
</div>)};
function md(t:string):string{let h=t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');h=h.replace(/```mermaid\n([\s\S]*?)```/g,(_,c:string)=>'<div class="mdb">'+c.trim()+'</div>');h=h.replace(/```(\w*)\n([\s\S]*?)```/g,(_,l:string,c:string)=>'<pre class="cb"><div class="cb-l">'+(l||'text')+'</div><code>'+hl(c.trim(),l)+'</code></pre>');h=h.replace(/`([^`]+)`/g,'<code>$1</code>');h=h.replace(/\*\*\*(.+?)\*\*\*/g,'<strong><em>$1</em></strong>');h=h.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');h=h.replace(/\*(.+?)\*/g,'<em>$1</em>');h=h.replace(/\$\$(.+?)\$\$/g,(_,f:string)=>'<div class="lx">'+f+'</div>');h=h.replace(/\$(.+?)\$/g,(_,f:string)=>'<span class="li">'+f+'</span>');h=h.replace(/^### (.+)/gm,'<h3>$1</h3>');h=h.replace(/^## (.+)/gm,'<h2>$1</h2>');h=h.replace(/^# (.+)/gm,'<h1>$1</h1>');h=h.replace(/^[-*] (.+)/gm,'<li>$1</li>');h=h.replace(/((?:<li>.*<\/li>\n?)+)/g,'<ul>$1</ul>');h=h.replace(/\n\n/g,'</p><p>');h=h.replace(/\n/g,'<br/>');return'<p>'+h+'</p>'}
function hl(c:string,l:string):string{const kw:Record<string,string[]>={js:['const','let','var','function','return','if','else','for','while','class','export','import','async','await','try','catch','throw','new','this'],py:['def','return','if','elif','else','for','while','class','import','from','async','await','try','except','raise','with','as','None','True','False'],ts:['const','let','var','function','return','if','else','for','while','class','export','import','async','await','try','catch','throw','new','this','interface','type','extends']};const w=kw[l]||[];let o=c;w.forEach(x=>{o=o.replace(new RegExp('\\b'+x+'\\b','g'),'<span class="hk">'+x+'</span>')});o=o.replace(/(\".*?\")/g,'<span class="hs">$1</span>');o=o.replace(/(\'.*?\')/g,'<span class="hs">$1</span>');o=o.replace(/(\/\/.*)/g,'<span class="hc">$1</span>');o=o.replace(/(\d+)/g,'<span class="hn">$1</span>');return o}
export default App;
