/**
 * Polaris Secret Vault
 * AES-256-GCM encrypted credentials. At runtime, decrypted into memory only.
 *
 * To update keys: run `node scripts/encrypt_secrets.js` with the new values.
 */
const { createCipheriv, createDecipheriv, randomBytes } = require('crypto');

// Derivation key — NOT the actual keys. This plus IV are the "lock" to the vault.
// An attacker would need BOTH the encrypted payloads AND this seed + IV to decrypt.
const VAULT_SEED = 'polaris_solver_bq7x_2026_agent_vault_k9';

// Encrypted payloads (generated by encrypting plaintext keys with the seed above)
// To regenerate, change the keys below and run: node -e "require('./electron/services/secrets').encryptAll()"
const VAULT = {
  deepseek_api_key: {
    iv:   '13ca87c48b736d5ffe826687',
    data: '788c9e2dc2de4453f8e6d5bac6569123ce35801a6fc4fbfe188b1e002c453f1d8a23c3',
    tag:  '985b9a80d130ae9a7628ad2419b90f23',
  },
  supabase_service_role: {
    iv:   'bf697152ecc41b7fc26961c2',
    data: 'ee4b0ff7e37dffd00bae1f9034f780eb399120f296857998a993800cb1ff510bf67d16e00fbaa5c719',
    tag:  '04986ab3c89fb4bd418f5301c609a985',
  },
  smtp_password: {
    iv:   '79c389a1836ec3b890bcc858',
    data: '8a2602f2e82e4f701af43d05eb24bbcd',
    tag:  'e272dda6ce6d510ef286482f27d11379',
  },
};

/* ── Internal ────────────────────────────────────────── */
function deriveKey() {
  const { createHash } = require('crypto');
  return createHash('sha256').update(VAULT_SEED).digest();
}

function decrypt(entry) {
  const key = deriveKey();
  const decipher = createDecipheriv('aes-256-gcm', key, Buffer.from(entry.iv, 'hex'));
  decipher.setAuthTag(Buffer.from(entry.tag, 'hex'));
  let decrypted = decipher.update(entry.data, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  return decrypted;
}

function encrypt(plaintext) {
  const key = deriveKey();
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  let encrypted = cipher.update(plaintext, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return { iv: iv.toString('hex'), data: encrypted, tag: cipher.getAuthTag().toString('hex') };
}

/* ── Public API ─────────────────────────────────────── */
let _cache = null;

function getAll() {
  if (_cache) return _cache;
  _cache = {};
  for (const name of Object.keys(VAULT)) {
    try { _cache[name] = decrypt(VAULT[name]); }
    catch (e) { console.error(`[Vault] Failed to decrypt ${name}:`, e.message); _cache[name] = ''; }
  }
  return _cache;
}

function get(name) { return getAll()[name] || ''; }

// CLI regenerator: pass keys as env vars, outputs encrypted VAULT snippet
//   POLARIS_NEW_DEEPSEEK=sk-xxx POLARIS_NEW_SB_SECRET=sb_xxx POLARIS_NEW_SMTP=xxx node -e "require('./electron/services/secrets').encryptAll()"
function encryptAll() {
  var keys = {
    deepseek_api_key:    process.env.POLARIS_NEW_DEEPSEEK || process.argv[2] || '',
    supabase_service_role: process.env.POLARIS_NEW_SB_SECRET || process.argv[3] || '',
    smtp_password:        process.env.POLARIS_NEW_SMTP || process.argv[4] || '',
  };
  for (var name in keys) { if (!keys[name]) { console.error('Missing key for ' + name); return; } }
  console.log('// Paste into electron/services/secrets.js → VAULT object:\n');
  for (var _i = 0, _names = Object.keys(keys); _i < _names.length; _i++) {
    var n2 = _names[_i];
    var e2 = encrypt(keys[n2]);
    console.log('  ' + n2 + ': {');
    console.log('    iv:   \'' + e2.iv + '\',');
    console.log('    data: \'' + e2.data + '\',');
    console.log('    tag:  \'' + e2.tag + '\',');
    console.log('  },');
  }
  console.log('\n// Done.');
}

module.exports = { get, getAll, encryptAll };
