/**
 * Polaris Secret Vault
 * AES-256-GCM encrypted credentials. At runtime, decrypted into memory only.
 *
 * To update keys: run `node scripts/encrypt_secrets.js` with the new values.
 */
const { createCipheriv, createDecipheriv, randomBytes } = require('crypto');

// Derivation key — NOT the actual keys. This plus IV are the "lock" to the vault.
// An attacker would need BOTH the encrypted payloads AND this seed + IV to decrypt.
const VAULT_SEED = 'polaris_solver_bq7x_2026_agent_vault_k9';

// Encrypted payloads (generated by encrypting plaintext keys with the seed above)
// To regenerate, change the keys below and run: node -e "require('./electron/services/secrets').encryptAll()"
const VAULT = {
  deepseek_api_key: {
    iv:   'b29cda8bce3d74e0b5e8724d',
    data: '559624d2d0a12a1dfcd2ce700a80c73ee027c6c9d5f20baa73a1dc77fc84586e99de1c',
    tag:  '6ad5a041c9c906c2bf0c654ca36e1885',
  },
  supabase_service_role: {
    iv:   '4e5830e1199d071701b56576',
    data: 'e408beb2ff079161fd2aa5e9e723cde2c45aa3d0e81bd1e202880b2e11325fcdafa77b5e12c5cfaf69',
    tag:  '544e805038a10bebffb5e57710d923f9',
  },
  smtp_password: {
    iv:   '3ae3f48b6b71dea2eecaa521',
    data: '773512feb2f64656f4b6badb45faeace',
    tag:  '9dd980c6a075ac5da6ae1f9a9a28cc01',
  },
};

/* ── Internal ────────────────────────────────────────── */
function deriveKey() {
  const { createHash } = require('crypto');
  return createHash('sha256').update(VAULT_SEED).digest();
}

function decrypt(entry) {
  const key = deriveKey();
  const decipher = createDecipheriv('aes-256-gcm', key, Buffer.from(entry.iv, 'hex'));
  decipher.setAuthTag(Buffer.from(entry.tag, 'hex'));
  let decrypted = decipher.update(entry.data, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  return decrypted;
}

function encrypt(plaintext) {
  const key = deriveKey();
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  let encrypted = cipher.update(plaintext, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return { iv: iv.toString('hex'), data: encrypted, tag: cipher.getAuthTag().toString('hex') };
}

/* ── Public API ─────────────────────────────────────── */
let _cache = null;

function getAll() {
  if (_cache) return _cache;
  _cache = {};
  for (const name of Object.keys(VAULT)) {
    try { _cache[name] = decrypt(VAULT[name]); }
    catch (e) { console.error(`[Vault] Failed to decrypt ${name}:`, e.message); _cache[name] = ''; }
  }
  return _cache;
}

function get(name) { return getAll()[name] || ''; }

// CLI regenerator: pass keys as env vars, outputs encrypted VAULT snippet
//   POLARIS_NEW_DEEPSEEK=sk-xxx POLARIS_NEW_SB_SECRET=sb_xxx POLARIS_NEW_SMTP=xxx node -e "require('./electron/services/secrets').encryptAll()"
function encryptAll() {
  var keys = {
    deepseek_api_key:    process.env.POLARIS_NEW_DEEPSEEK || process.argv[2] || '',
    supabase_service_role: process.env.POLARIS_NEW_SB_SECRET || process.argv[3] || '',
    smtp_password:        process.env.POLARIS_NEW_SMTP || process.argv[4] || '',
  };
  for (var name in keys) { if (!keys[name]) { console.error('Missing key for ' + name); return; } }
  console.log('// Paste into electron/services/secrets.js → VAULT object:\n');
  for (var _i = 0, _names = Object.keys(keys); _i < _names.length; _i++) {
    var n2 = _names[_i];
    var e2 = encrypt(keys[n2]);
    console.log('  ' + n2 + ': {');
    console.log('    iv:   \'' + e2.iv + '\',');
    console.log('    data: \'' + e2.data + '\',');
    console.log('    tag:  \'' + e2.tag + '\',');
    console.log('  },');
  }
  console.log('\n// Done.');
}

module.exports = { get, getAll, encryptAll };
