/**
 * Polaris Secret Vault
 * AES-256-GCM encrypted credentials. At runtime, decrypted into memory only.
 *
 * To update keys: run `node scripts/encrypt_secrets.js` with the new values.
 */
const { createCipheriv, createDecipheriv, randomBytes } = require('crypto');

// Derivation key — NOT the actual keys. This plus IV are the "lock" to the vault.
// An attacker would need BOTH the encrypted payloads AND this seed + IV to decrypt.
const VAULT_SEED = 'polaris_solver_bq7x_2026_agent_vault_k9';

// Encrypted payloads (generated by encrypting plaintext keys with the seed above)
// To regenerate, change the keys below and run: node -e "require('./electron/services/secrets').encryptAll()"
const VAULT = {
  deepseek_api_key: {
    iv:   'dd92ccb9dac16038a7a8c626',
    data: '3cf4a8818b97a4f1331bad787cdbfdc9e043bb15447f4120d792193a69a6287e742577',
    tag:  'da7e70b62d65c351ea0eeba1284b0af7',
  },
  supabase_service_role: {
    iv:   '0747d60af59139471769ca60',
    data: '4ff15280a0726cd6fa890c53dd7ded39104a9a57de279c33edf0922f9ea32c19669cf11be489be0982',
    tag:  '11d65aad6640757703250f470cc43d54',
  },
  smtp_password: {
    iv:   '5dd003360cfe51c8b36c48eb',
    data: '0efb6458d1533ef1642374b2debbb5a0',
    tag:  'ab17bde1f322833caa2d57b8f4cbf2cd',
  },
};

/* ── Internal ────────────────────────────────────────── */
function deriveKey() {
  const { createHash } = require('crypto');
  return createHash('sha256').update(VAULT_SEED).digest();
}

function decrypt(entry) {
  const key = deriveKey();
  const decipher = createDecipheriv('aes-256-gcm', key, Buffer.from(entry.iv, 'hex'));
  decipher.setAuthTag(Buffer.from(entry.tag, 'hex'));
  let decrypted = decipher.update(entry.data, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  return decrypted;
}

function encrypt(plaintext) {
  const key = deriveKey();
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  let encrypted = cipher.update(plaintext, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return { iv: iv.toString('hex'), data: encrypted, tag: cipher.getAuthTag().toString('hex') };
}

/* ── Public API ─────────────────────────────────────── */
let _cache = null;

function getAll() {
  if (_cache) return _cache;
  _cache = {};
  for (const name of Object.keys(VAULT)) {
    try { _cache[name] = decrypt(VAULT[name]); }
    catch (e) { console.error(`[Vault] Failed to decrypt ${name}:`, e.message); _cache[name] = ''; }
  }
  return _cache;
}

function get(name) { return getAll()[name] || ''; }

// CLI regenerator: pass keys as env vars, outputs encrypted VAULT snippet
//   POLARIS_NEW_DEEPSEEK=sk-xxx POLARIS_NEW_SB_SECRET=sb_xxx POLARIS_NEW_SMTP=xxx node -e "require('./electron/services/secrets').encryptAll()"
function encryptAll() {
  var keys = {
    deepseek_api_key:    process.env.POLARIS_NEW_DEEPSEEK || process.argv[2] || '',
    supabase_service_role: process.env.POLARIS_NEW_SB_SECRET || process.argv[3] || '',
    smtp_password:        process.env.POLARIS_NEW_SMTP || process.argv[4] || '',
  };
  for (var name in keys) { if (!keys[name]) { console.error('Missing key for ' + name); return; } }
  console.log('// Paste into electron/services/secrets.js → VAULT object:\n');
  for (var _i = 0, _names = Object.keys(keys); _i < _names.length; _i++) {
    var n2 = _names[_i];
    var e2 = encrypt(keys[n2]);
    console.log('  ' + n2 + ': {');
    console.log('    iv:   \'' + e2.iv + '\',');
    console.log('    data: \'' + e2.data + '\',');
    console.log('    tag:  \'' + e2.tag + '\',');
    console.log('  },');
  }
  console.log('\n// Done.');
}

module.exports = { get, getAll, encryptAll };
